@03-passwordapi-aspnet_HostAddress = http://localhost:5265

GET {{03-passwordapi-aspnet_HostAddress}}/weatherforecast/
Accept: application/json

### Регистрация пользователя
POST http://localhost:5265/api/auth/register
Content-Type: application/json

{
  "userName": "testuser",
  "password": "password123"
}

### Вход пользователя
POST http://localhost:5265/api/auth/login
Content-Type: application/json

{
  "userName": "testuser",
  "password": "password123"
}

### Получение списка пользователей
GET http://localhost:5265/api/auth/users